### PR TITLE
fix: typo with type and set color

### PR DESCRIPTION
**Pull request by peterpeterparker**

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Seems alright or I am missing something?

Capture d’écran 2021-06-02 à 21 26 03

**Comment by peterpeterparker** [comment]
iphone too

Capture d’écran 2021-06-02 à 21 29 02

**Comment by sansan88** [comment]
grafik

**Comment by sansan88** [comment]
the ion-input has an ugly border/style when I add the type attribute. I provided a better example in master branch

**Comment by peterpeterparker** [comment]
@sansan88 tailwind does not know about the ionic components and, adds default styling to focused inputs per default which does not play well together


Capture d’écran 2021-06-02 à 21 36 19

you have to customize it to fits your need I would say

not a big fan of `ng-deep` as it can be deprecated some day but something like  following does the job

```
ion-input::ng-deep input[type="text"]:focus {
  box-shadow: none;
}
```

Capture d’écran 2021-06-02 à 21 47 02

**Comment by sansan88** [comment]
Ohhh gosh.. 😅
I need to further investigate this.. it's not only on focused elements. 
But thank you anyway! I'll implement your solution

**Comment by sansan88** [comment]
Based on my global.scss file, ionic is missing some css declarations, when type is set

**Comment by peterpeterparker** [comment]
It's just a rough suggestion, there might be better way to integrate tailwind with ionic to make them play well together

Checkout these demo repo, I think max (maybe?) made a demo a couple of months ago

**Comment by peterpeterparker** [comment]
In this particular case the css were not missing but were overriden by by tailwind defaults

Good luck!

**Comment by peterpeterparker** [comment]
side note: another option would maybe be to not use `ion-input`but only `input` btw.

**Comment by sansan88** [comment]
https://github.com/mlynch/nextjs-tailwind-ionic-capacitor-starter

**Pull request closed without merging**
